// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: H743_SmartStation_UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_btn_click_increment(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
