// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: H743_SmartStation_UI

#include "ui.h"
#include "widgets/label/lv_label.h"

void on_btn_click_increment(lv_event_t * e)
{

}
