// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: H743_SmartStation_UI

#include "../ui.h"

lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_uiBgPanel = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiBgPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiBgPanel, 320);
    lv_obj_set_height(ui_uiBgPanel, 480);
    lv_obj_set_x(ui_uiBgPanel, -325);
    lv_obj_set_y(ui_uiBgPanel, -3);
    lv_obj_set_align(ui_uiBgPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_uiBgPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_opa(ui_uiBgPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_uiBgPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -111);
    lv_obj_set_y(ui_Label1, 179);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "12:15");

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -50);
    lv_obj_set_y(ui_Switch1, 178);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    uic_Screen1 = ui_Screen1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    ui_uiBgPanel = NULL;
    ui_Label1 = NULL;
    ui_Switch1 = NULL;

}
