// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: H743_SmartStation_UI

#include "../ui.h"
#include "core/lv_obj.h"
#include "misc/lv_types.h"
#include "widgets/button/lv_button.h"

lv_obj_t * uic_Image3;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Hello_H743 = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 1);
    lv_obj_set_y(ui_Button1, -7);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hello_H743 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Hello_H743, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hello_H743, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hello_H743, 0);
    lv_obj_set_y(ui_Hello_H743, -69);
    lv_obj_set_align(ui_Hello_H743, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hello_H743, "text");

    ui_Image3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image3, &ui_img_1598979325);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 7);
    lv_obj_set_y(ui_Image3, -163);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Screen1 = ui_Screen1;
    uic_Image3 = ui_Image3;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Hello_H743 = NULL;
    uic_Image3 = NULL;
    ui_Image3 = NULL;

}
